import React from "react";
import Navbar from "../../page/home/navbar";
import azure_bg from "../../assets/Services/Azure/azure_bg.webp";
import azure01 from "../../assets/Services/Azure/azure01.webp";
import azure02 from "../../assets/Services/Azure/azure02.webp";
import azure03 from "../../assets/Services/Azure/azure03.webp";
import azure04 from "../../assets/Services/Azure/azure04.webp";
import azure05 from "../../assets/Services/Azure/azure05.webp";
import azure_avt01 from "../../assets/Services/Azure/azure_avt01.webp";
import azure_avt02 from "../../assets/Services/Azure/azure_avt02.webp";
import azure_avt03 from "../../assets/Services/Azure/azure_avt03.webp";
import azure_avt04 from "../../assets/Services/Azure/azure_avt04.webp";
import azure_avt05 from "../../assets/Services/Azure/azure_avt05.webp";
import { Fade, Slide } from "react-awesome-reveal";
import { Avatar, Grid, Typography } from "@mui/material";
import { useState } from "react";
import DialogOpen from "../../components/DialogOpen";
import Footer from "../../page/home/Footer";

function Azure() {
  const popUpData = [
    {
      id: 1,
      title: "Azure IoT Hub Seamless Device Connectivity at Scale",
      content:
        "We assist you in connecting and managing your devices effortlessly, facilitating secure communication between devices and the cloud. From industrial machinery to consumer gadgets, our experts ensure your devices are not only connected but also safeguarded with robust security measures.",
      service: [
        "Device provisioning and registration.",
        "Secure bi-directional communication with MQTT and AMQP.",
        "Device twin management for real-time synchronization.",
        "Integration with Azure Active Directory for access control.",
      ],
    },
    {
      id: 2,
      title:
        "Azure Stream Analytics Real-Time Data Processing for IoT Insights",
      content:
        "Leverage the power of Azure Stream Analytics to process and analyze real-time data from your IoT devices. With our expertise, you can design and deploy scalable, real-time data pipelines that extract valuable insights from your data streams, enabling you to make informed decisions swiftly.",
      service: [
        "Pipeline design and deployment for real-time data processing.",
        "Integration with Azure Event Hubs and IoT Hub for data ingestion.",
        "Complex event processing and anomaly detection.",
        "Integration with Azure Machine Learning for predictive analytics.",
      ],
    },

    {
      id: 3,
      title: "Python Lambda Function Services",
      content:
        "Efficiency is key in IoT operations. Our Python Lambda function development services allow you to automate data processing, analysis, and transformation in response to IoT events. We create custom Lambda functions that integrate seamlessly with your AWS IoT environment, ensuring that your workflows are streamlined and optimized.",
      service: [
        "Event-driven Lambda function development.",
        "Data transformation, validation, and enrichment.",
        "Integration with AWS services such as DynamoDB and S3.",
        "Real-time data analytics using Lambda and other AWS services.",
      ],
    },

    {
      id: 4,
      title: "Amazon Timestream Services",
      content:
        "Amazon Timestream is the ideal solution for managing and querying time-series data generated by your IoT devices. Our experts help you set up and configure Timestream databases, allowing you to efficiently store, analyze, and visualize time-stamped data. With Timestream, you can unlock valuable insights and trends from your IoT-generated data.",
      service: [
        "Database creation and schema design for time-series data.",
        "Data ingestion and batch processing setup.",
        "Integration with visualization tools and business intelligence platforms.",
        "Query optimization for fast and accurate data retrieval.",
      ],
    },
    {
      id: 5,
      title: "API Gateway Services",
      content:
        "API Gateway acts as the bridge between your IoT devices and external applications. Our API Gateway services enable you to create and manage APIs that allow secure and controlled access to your IoT data. Whether you're exposing data to partners, customers, or internal applications, we ensure that your APIs are secure, scalable, and reliable.",
      service: [
        "API design and creation to expose IoT data.",
        "Secure API authentication and authorization. Rate limiting and throttling to control access.",
        "Integration with AWS Lambda for real-time data processing.",
      ],
    },
  ];

  const [openPopup, setOpenPopup] = useState(false);
  const [data, setData] = useState([]);

  const handleClose = () => {
    setOpenPopup(false);
  };
  return (
    <>
      <Navbar />
      <section className="homepage">
        <img
          src={azure_bg}
          alt="Digikloud Company"
          className="services_background_image"
        />
        <header className="servicesTopHead">
          <Fade direction="up" duration={2000} triggerOnce={true}>
            <Typography variant="h1">
              Welcome to DiGiKloud- Your Gateway to Azure IoT Excellence
            </Typography>
          </Fade>
        </header>
      </section>

      <section className="byoppagecontainer">
        <Grid container className="azure_services_container">
          <Grid item xs={12} md={4} lg={4}>
            <Fade direction="up" triggerOnce={true} duration={1000}>
              <article
                className="awsIot_services_container"
                onClick={() => {
                  setOpenPopup(true);
                  setData(popUpData[0]);
                }}
              >
                {/* <img src={azure01} height='100px' width='100px'  /> */}
                <Avatar
                  sx={{ width: "100px", height: "100px" }}
                  src={azure_avt01}
                />
                <Typography variant="h6"> Azure IoT Hub</Typography>
                <Typography variant="p">
                  Azure IoT Hub is the cornerstone of your IoT deployment.
                </Typography>
              </article>
            </Fade>
          </Grid>
          <Grid item xs={12} md={4} lg={4}>
            <Fade direction="up" triggerOnce={true} duration={2000}>
              <article
                className="awsIot_services_container"
                onClick={() => {
                  setOpenPopup(true);
                  setData(popUpData[1]);
                }}
              >
                <Avatar
                  sx={{ width: "100px", height: "100px" }}
                  src={azure_avt02}
                />
                <Typography variant="h6">Azure Stream Analytics</Typography>
                <Typography variant="p">
                  Leverage the power of Azure Stream Analytics to process data
                  from your IoT devices
                </Typography>
              </article>
            </Fade>
          </Grid>
          <Grid item xs={12} md={4} lg={4}>
            <Fade direction="up" triggerOnce={true} duration={2000}>
              <article
                className="awsIot_services_container"
                onClick={() => {
                  setOpenPopup(true);
                  setData(popUpData[2]);
                }}
              >
                <Avatar
                  sx={{ width: "100px", height: "100px" }}
                  src={azure_avt03}
                />
                <Typography variant="h6">Azure Functions</Typography>
                <Typography variant="p">
                  Efficiency is paramount in IoT operations.
                </Typography>
              </article>
            </Fade>
          </Grid>
          <Grid item xs={12} md={6} lg={6}>
            <Fade direction="up" triggerOnce={true} duration={2000}>
              <article
                className="awsIot_services_container"
                onClick={() => {
                  setOpenPopup(true);
                  setData(popUpData[3]);
                }}
              >
                <Avatar
                  sx={{ width: "100px", height: "100px" }}
                  src={azure_avt04}
                />
                <Typography variant="h6">
                  {" "}
                  Azure Time Series Insights
                </Typography>
                <Typography variant="p">
                  Azure Time Series Insights is your solution for analyzing, and
                  visualizing data generated by IoT devices
                </Typography>
              </article>
            </Fade>
          </Grid>
          <Grid item xs={12} md={6} lg={6}>
            <Fade direction="up" triggerOnce={true} duration={2000}>
              <article
                className="awsIot_services_container"
                onClick={() => {
                  setOpenPopup(true);
                  setData(popUpData[4]);
                }}
              >
                <Avatar
                  sx={{ width: "100px", height: "100px" }}
                  src={azure_avt05}
                />
                <Typography variant="h6">Azure API Management</Typography>
                <Typography variant="p">
                  Azure API Management acts as the bridge between your IoT
                  devices and external applications.
                </Typography>
              </article>
            </Fade>
          </Grid>
        </Grid>
      </section>
      <section>
        <article className="byoppagecontainer">
          <Grid container className="azure_services_container">
            <Grid
              item
              xs={12}
              md={6}
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <Slide direction="left" triggerOnce={true} duration={1500}>
                <img src={azure01} alt="" />
              </Slide>
            </Grid>
            <Grid item xs={12} md={6} >
              <Slide direction="right" triggerOnce={true} duration={1500}>
                <h3 className="homepageSubhead">
                  Azure IoT Hub Seamless Device Connectivity at Scale
                </h3>
                <Typography variant="p" align="justify">
                  We assist you in connecting and managing your devices
                  effortlessly, facilitating secure communication between
                  devices and the cloud. From industrial machinery to consumer
                  gadgets, our experts ensure your devices are not only
                  connected but also safeguarded with robust security measures.
                </Typography>
                <ul style={{ lineHeight: "2" }}>
                  <li>Device provisioning and registration.</li>
                  <li>
                    Secure bi-directional communication with MQTT and AMQP.
                  </li>
                  <li>Device twin management for real-time synchronization.</li>
                  <li>
                    Integration with Azure Active Directory for access control.
                  </li>
                </ul>
              </Slide>
            </Grid>
          </Grid>
        </article>
      </section>

      <section>
        <article className="byoppagecontainer">
          <Grid container className="azure_services_container">
            <Grid item xs={12} md={6} >
              <Slide direction="left" triggerOnce={true} duration={1500}>
                <h3 className="homepageSubhead">
                  Azure API Management Secure and Scalable APIs for Your IoT
                  Ecosystem
                </h3>
                <Typography variant="p" align="justify">
                  Azure API Management acts as the bridge between your IoT
                  devices and external applications. Our Azure API Management
                  services empower you to create, publish, and manage APIs that
                  provide secure and controlled access to your IoT data. Whether
                  you're exposing data to partners, customers, or internal
                  applications, we ensure your APIs are secure, scalable, and
                  reliable.
                </Typography>
                <ul style={{ lineHeight: "2" }}>
                  <li>API design and creation to expose IoT data.</li>
                  <li>Secure API authentication and authorization.</li>
                  <li>Rate limiting and throttling to control access.</li>
                  <li>
                    Integration with Azure Functions for real-time data
                    processing.
                  </li>
                </ul>
              </Slide>
            </Grid>
            <Grid
              item
              xs={12}
              md={6}
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <Slide direction="right" triggerOnce={true} duration={1500}>
                <img src={azure02} alt="" />
              </Slide>
            </Grid>
          </Grid>
        </article>
      </section>

      <section>
        <article className="byoppagecontainer">
          <Grid container className="azure_services_container">
            <Grid
              item
              xs={12}
              md={6}
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <Slide direction="left" triggerOnce={true} duration={1500}>
                <img src={azure03} alt="" />
              </Slide>
            </Grid>
            <Grid item xs={12} md={6} >
              <Slide direction="right" triggerOnce={true} duration={1500}>
                <h3 className="homepageSubhead">
                  Azure Stream Analytics Real-Time Data Processing for IoT
                  Insights
                </h3>
                <Typography variant="p" align="justify">
                  Leverage the power of Azure Stream Analytics to process and
                  analyze real-time data from your IoT devices. With our
                  expertise, you can design and deploy scalable, real-time data
                  pipelines that extract valuable insights from your data
                  streams, enabling you to make informed decisions swiftly.
                </Typography>
                <ul style={{ lineHeight: "2" }}>
                  <li>
                    Pipeline design and deployment for real-time data
                    processing.
                  </li>
                  <li>
                    Integration with Azure Event Hubs and IoT Hub for data
                    ingestion.
                  </li>
                  <li>Complex event processing and anomaly detection.</li>
                  <li>
                    Integration with Azure Machine Learning for predictive
                    analytics.
                  </li>
                </ul>
              </Slide>
            </Grid>
          </Grid>
        </article>
      </section>

      <section>
        <article className="byoppagecontainer">
          <Grid container className="azure_services_container">
            <Grid item xs={12} md={6} >
              <Slide direction="left" triggerOnce={true} duration={1500}>
                <h3 className="homepageSubhead">
                  Azure Functions Event-Driven Automation for IoT Workflows
                </h3>
                <Typography variant="p" align="justify">
                  Efficiency is paramount in IoT operations. Our Azure Functions
                  development services allow you to automate data processing,
                  analysis, and actions in response to IoT events. We create
                  custom Azure Functions that seamlessly integrate with your
                  Azure IoT environment, ensuring streamlined workflows and
                  optimized operations..
                </Typography>
                <ul style={{ lineHeight: "2" }}>
                  <li>Event-driven function development for IoT workflows.</li>
                  <li>Data transformation, validation, and enrichment.</li>
                  <li>
                    Integration with Azure services such as Azure Storage and
                    Cosmos DB.
                  </li>
                  <li>
                    Real-time data analytics using Azure Functions and other
                    services.
                  </li>
                </ul>
              </Slide>
            </Grid>
            <Grid
              item
              xs={12}
              md={6}
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <Slide direction="right" triggerOnce={true} duration={1500}>
                <img src={azure04} alt="" />
              </Slide>
            </Grid>
          </Grid>
        </article>
      </section>

      <section>
        <article className="byoppagecontainer">
          <Grid container className="azure_services_container">
            <Grid
              item
              xs={12}
              md={6}
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <Slide direction="left" triggerOnce={true} duration={1500}>
                <img src={azure05} alt="" />
              </Slide>
            </Grid>
            <Grid item xs={12} md={6} >
              <Slide direction="right" triggerOnce={true} duration={1500}>
                <h3 className="homepageSubhead">
                  Azure Time Series Insights Uncover Insights from Time-Series
                  Data
                </h3>
                <Typography variant="p" align="justify">
                  Azure Time Series Insights is your solution for managing,
                  analyzing, and visualizing time-stamped data generated by IoT
                  devices. Our experts assist you in setting up and configuring
                  Time Series Insights environments, enabling you to efficiently
                  store, explore, and interpret time-series data for actionable
                  insights.
                </Typography>
                <ul style={{ lineHeight: "2" }}>
                  <li>
                    Environment setup and schema design for time-series data.
                  </li>
                  <li>Data ingestion and exploration configuration.</li>
                  <li>
                    Integration with visualization tools and Power BI for
                    insightful dashboards.
                  </li>
                  <li>Query optimization for fast data retrieval.</li>
                </ul>
              </Slide>
            </Grid>
          </Grid>
        </article>
      </section>

      <Footer />
      <DialogOpen
        openPopup={openPopup}
        onClose={handleClose}
        title={data.title}
        content={data.content}
        contentList={data.service}
      ></DialogOpen>
    </>
  );
}

export default Azure;
